/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          bg: "#0d0d0b",
          card: "#161614",
          border: "#261e1b",
          primary: "#e8a838",
          teal: "#f2dfa8",
          success: "#22c55e",
          warning: "#f97316",
          danger: "#ef4444",
          muted: "#a59a96",
        },
        "secondary-container": "#be8623",
        "inverse-on-surface": "#31302e",
        "tertiary-container": "#c4b37f",
        "outline": "#9d8e7c",
        "on-tertiary-fixed-variant": "#52461d",
        "primary-fixed-dim": "#fdba49",
        "on-tertiary-fixed": "#231b00",
        "surface": "#141311",
        "surface-container-highest": "#353532",
        "surface-bright": "#3a3937",
        "background": "#141311",
        "on-primary-fixed-variant": "#614000",
        "surface-container-high": "#2a2a28",
        "surface-container-low": "#1c1c19",
        "on-secondary-container": "#3b2500",
        "secondary-fixed": "#ffddb0",
        "primary-fixed": "#ffddaf",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#281800",
        "surface-variant": "#353532",
        "secondary": "#fbbb55",
        "on-surface-variant": "#d5c4af",
        "primary": "#ffc66b",
        "tertiary-fixed-dim": "#d7c590",
        "surface-tint": "#fdba49",
        "surface-container-lowest": "#0e0e0c",
        "primary-container": "#e8a838",
        "secondary-fixed-dim": "#fbbb55",
        "inverse-surface": "#e5e2de",
        "on-secondary-fixed-variant": "#614000",
        "tertiary": "#e1ce99",
        "error-container": "#93000a",
        "on-primary": "#432c00",
        "surface-dim": "#141311",
        "on-error": "#690005",
        "on-surface": "#e5e2de",
        "error": "#ffb4ab",
        "on-tertiary": "#3a2f08",
        "tertiary-fixed": "#f4e1aa",
        "on-background": "#e5e2de",
        "inverse-primary": "#805600",
        "on-secondary": "#442c00",
        "on-tertiary-container": "#51451c",
        "on-secondary-fixed": "#281800",
        "on-primary-container": "#5f3f00",
        "surface-container": "#20201d",
        "outline-variant": "#504535",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
