/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline": ["Cormorant Garamond", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Sora", "sans-serif"]
      },
      colors: {
        brand: {
          bg: "#fdf9f1",
          card: "#ffffff",
          border: "#e6e2da",
          primary: "#A07154",
          teal: "#00c9a7",
          success: "#22c55e",
          warning: "#f97316",
          danger: "#ef4444",
          muted: "#837563",
          text: "#1c1c17",
        },
        coffee: {
          dark: "#38251C",
          darker: "#251811",
          cream: "#F4EBE1",
          card: "#FDF9F3",
          accent: "#A07154",
          btn: "#825C43",
          text: "#2C1E16",
        },
        "on-primary-fixed-variant": "#614000",
        "tertiary-fixed": "#ffdcc3",
        "on-surface": "#1c1c17",
        "on-secondary-container": "#596468",
        "tertiary-container": "#d9aa87",
        "secondary": "#556064",
        "surface-variant": "#e6e2da",
        "secondary-container": "#d6e2e6",
        "primary-fixed-dim": "#fdba49",
        "inverse-surface": "#31302b",
        "tertiary-fixed-dim": "#edbd99",
        "on-tertiary-fixed": "#2e1501",
        "primary": "#805600",
        "on-background": "#1c1c17",
        "surface-container-high": "#ece8e0",
        "outline-variant": "#d5c4af",
        "surface-container-highest": "#e6e2da",
        "on-error-container": "#93000a",
        "on-primary-container": "#5f3f00",
        "on-tertiary-container": "#5f3e23",
        "on-primary-fixed": "#281800",
        "secondary-fixed": "#d9e4e9",
        "surface-dim": "#dddad2",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3e484c",
        "background": "#fdf9f1",
        "on-secondary-fixed": "#131d21",
        "inverse-primary": "#fdba49",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#613f24",
        "inverse-on-surface": "#f4f0e8",
        "surface-container": "#f1ede5",
        "surface": "#fdf9f1",
        "surface-bright": "#fdf9f1",
        "primary-container": "#e8a838",
        "on-primary": "#ffffff",
        "surface-tint": "#805600",
        "surface-container-low": "#f7f3eb",
        "error-container": "#ffdad6",
        "tertiary": "#7b5639",
        "secondary-fixed-dim": "#bdc8cd",
        "outline": "#837563",
        "primary-fixed": "#ffddaf",
        "on-surface-variant": "#504535"
      },
    },
  },
  plugins: [],
};
