const PDFDocument = require('pdfkit');

/**
 * Export sales report as PDF
 * @param {import('express').Response} res - Express response
 * @param {object} data - Report data
 */
async function exportSalesReportPDF(res, data) {
  const { title, period, totalSales, orders } = data;

  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Set response headers
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=sales-report-${period}.pdf`);

  doc.pipe(res);

  // Header
  doc.fontSize(24).font('Helvetica-Bold').text('POS Cafe', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(16).font('Helvetica').text(title, { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#666666').text(`Period: ${period} | Generated: ${new Date().toLocaleString()}`, { align: 'center' });
  doc.moveDown(1);

  // Divider
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
  doc.moveDown(1);

  // Summary
  doc.fontSize(14).fillColor('#000000').font('Helvetica-Bold').text('Summary');
  doc.moveDown(0.5);
  doc.fontSize(11).font('Helvetica');
  doc.text(`Total Sales: $${totalSales.toFixed(2)}`);
  doc.text(`Total Orders: ${orders.length}`);
  doc.text(`Average Order Value: $${orders.length > 0 ? (totalSales / orders.length).toFixed(2) : '0.00'}`);
  doc.moveDown(1);

  // Divider
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
  doc.moveDown(1);

  // Orders Table Header
  doc.fontSize(14).font('Helvetica-Bold').text('Order Details');
  doc.moveDown(0.5);

  // Table header
  const tableTop = doc.y;
  const col1 = 50;   // Order #
  const col2 = 160;  // Table
  const col3 = 230;  // Cashier
  const col4 = 330;  // Amount
  const col5 = 420;  // Payment
  const col6 = 490;  // Date

  doc.fontSize(9).font('Helvetica-Bold').fillColor('#333333');
  doc.text('Order #', col1, tableTop);
  doc.text('Table', col2, tableTop);
  doc.text('Cashier', col3, tableTop);
  doc.text('Amount', col4, tableTop);
  doc.text('Payment', col5, tableTop);
  doc.text('Date', col6, tableTop);

  doc.moveTo(50, tableTop + 15).lineTo(545, tableTop + 15).stroke('#cccccc');

  // Table rows
  let y = tableTop + 22;
  doc.font('Helvetica').fillColor('#000000').fontSize(8);

  const maxRows = Math.min(orders.length, 50); // Limit to 50 rows per page
  for (let i = 0; i < maxRows; i++) {
    const order = orders[i];

    if (y > 750) {
      doc.addPage();
      y = 50;
    }

    doc.text(order.orderNumber, col1, y, { width: 100 });
    doc.text(order.table?.tableNumber || '-', col2, y, { width: 60 });
    doc.text(order.createdByUser?.name || '-', col3, y, { width: 90 });
    doc.text(`$${Number(order.totalAmount).toFixed(2)}`, col4, y, { width: 80 });
    doc.text(order.payments?.[0]?.paymentMethod?.name || '-', col5, y, { width: 60 });
    doc.text(new Date(order.createdAt).toLocaleDateString(), col6, y, { width: 60 });

    y += 18;
  }

  if (orders.length > 50) {
    doc.moveDown(1);
    doc.fontSize(9).fillColor('#999999').text(`... and ${orders.length - 50} more orders`);
  }

  // Footer
  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999999').text(
    'Generated by POS Cafe System',
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();
}

module.exports = { exportSalesReportPDF };
